from leplusorg/kali

RUN apt-get update
RUN apt-get install -y python3 python3-venv
ENV TASKLIST=""
ENV PACKAGES="[]"
ENV AGENTID=""
WORKDIR /usr/src/app
COPY ./agent.py ./
COPY ./requirements.txt ./
RUN python3 -m venv /opt/env
ENV PATH="/opt/env/bin:$PATH"
RUN pip install -r requirements.txt
CMD ["python3", "agent.py"]
