# Generated by Django 5.1.2 on 2024-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="detailed",
            new_name="Detailed",
        ),
        migrations.AddField(
            model_name="user",
            name="counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="information",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="resultData",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="jobState",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("error", "Error"),
                    ("expired", "Expired"),
                    ("active", "Active"),
                    ("waiting", "Waiting"),
                ],
                default="waiting",
                max_length=7,
            ),
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
