# Generated by Django 5.1.2 on 2024-10-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_delete_report_rename_detailed_user_detailed_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserReg",
        ),
    ]
