# Generated by Django 5.1.2 on 2024-10-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_rename_user_userreg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserReg",
        ),
    ]
